required_settings:
  input_path: ./meshes/mesh_lods/s0         # Path to lod 0 meshes or multiscale meshes
  output_path: ./meshes   # Path to write out multires meshes
  num_lods: 2                          # Number of levels of detail
  box_size: 8                          # lod 0 box size
optional_decimation_settings:
  skip_decimation: False         # Skip mesh decimation if meshes exist; default is false
  decimation_factor: 2           # Factor by which to decimate faces at each lod, ie factor**lod; default is 2
  aggressiveness: 10             # Aggressiveness to be used for decimation; default is 7
  delete_decimated_meshes: False  # Delete decimated meshes, only applied if skip_decimation=False
