version: "3.3"

services:
  preprocessing-watchdog:
    image: preprocessing:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /market-file/datasets:/remote/input
      - /market-file/staging:/remote/staging
      - /home/ubuntu/workspace/preprocessing/pipeline/mongo_config.json:/app/mongo_config.json
      - /imp-data/folderhost/:/hosting
    entrypoint: >
      sh -c "/usr/local/bin/_entrypoint.sh python processor.py /remote/input /remote/staging /hosting /app/mongo_config.json -t"
