name: preprocessing
channels:
  - open3d-admin
  - flyem-forge
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # - python=3.9
  - numpy 
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - scikit-image
  - tifffile
  - mrcfile
  - trimesh
  - joblib
  - psutil
  - tqdm
  # - cython
  # - make
  - watchdog
  - pymongo
  - pip
  - pip:
    - tinybrain
    - cloud-volume==8.7.0
    - starfile
    - pandarallel
    # - pyfqmr
    # - git+https://github.com/mitchellshargreaves-monash/multiresolution-mesh-creator
