name: preprocessing
channels:
  - open3d-admin
  - flyem-forge
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # - python=3.9
  # - numpy 
  # - pandas
  # - scipy
  # - scikit-learn
  - scikit-image
  # - trimesh
  - matplotlib
  - mrcfile
  # - joblib
  # - psutil
  # - tqdm
  # - tifffile
  - watchdog
  # - cython
  # - make
  - pip
  - pip:
    - tinybrain
    - cloud-volume==8.7.0
    # - pyfqmr
    # - git+https://github.com/mitchellshargreaves-monash/multiresolution-mesh-creator
